Musicorum/Musicorum/Controllers/EventsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Musicorum.Services;
using Musicorum.Services.Models;
using Musicorum.Web.Extensions;
using Musicorum.Web.Infrastructure.Filters;
using Musicorum.Web.Models.Events;

namespace Musicorum.Web.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        private readonly IEventService eventService;

        public EventsController(IEventService eventService)
        {
            this.eventService = eventService;
        }

        public IActionResult AddEvent()
        {
            return PartialView("_CreateEvent");
        }

        [HttpPost]
        public IActionResult AddEvent(EventFormModel model)
        {
            this.eventService.Create(
                model.ImageUrl,
                model.Title,
                model.Location,
                model.Description,
                model.DateStarts,
                model.DateEnds,
                model.Photos,
                model.Videos);

            return RedirectToAction("Index", "Admin", new { categoryId = 4 });
        }

        [HttpGet]
        public IActionResult EditEvent(int eventId)
        {
            EventModel ev = this.eventService.EventById(eventId);

            EventFormModel model = new EventFormModel
            {
                EventId = ev.Id,
                ImageUrl = ev.ImageUrl,
                Title = ev.Title,
                Location = ev.Location,
                Description = ev.Description,
                DateEnds = ev.DateEnds,
                DateStarts = ev.DateStarts,
            };

            return PartialView("_EditEvent", model);
        }

        [HttpPost]
        public IActionResult EditEvent(EventFormModel model)
        {
            this.eventService.Edit(
                model.EventId,
                model.ImageUrl,
                model.Title,
                model.Location,
                model.Description,
                model.DateStarts,
                model.DateEnds,
                model.Photos,
                model.Videos);

            return RedirectToAction("Index", "Admin", new { categoryId = 4 });
        }

        [HttpDelete]
        public IActionResult DeleteEvent(int eventId)
        {
            this.eventService.Delete(eventId);

            return Json(new { message = "Успішно видалено" });
        }

        [HttpGet]
        public IActionResult GetEvent(int eventId)
        {
            EventModel ev = this.eventService.EventById(eventId);

            return View("EventPage", ev);
        }

        public IActionResult Details(int id)
        {
            if (!this.eventService.Exists(id))
            {
                return NotFound();
            }

            return Ok();
        }

        public IActionResult JointEvent(int id)
        {
            if (!this.eventService.Exists(id))
            {
                return NotFound();
            }


            return RedirectToAction(nameof(Details), new { id = id });
        }
    }
}

Musicorum/Musicorum/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Musicorum.Services;
using Musicorum.Services.Models;
using Musicorum.Web.Models.News;

namespace Musicorum.Web.Controllers
{
    public class NewsController : Controller
    {
        private const int take = 1;

        private readonly INewsService newsService;

        public NewsController(INewsService newsService)
        {
            this.newsService = newsService;
        }

        public IActionResult Index()
        {
            IList<NewsModel> news = this.newsService.GetNewsWithTake(0, take);
            long newsShown = this.newsService.GetNewsWithTake(0, take).Count;
            long newsCount = this.newsService.CountAllNews();

            NewsPageModel model = new NewsPageModel
            {
                Skip = take,
                HasMore = newsCount > newsShown,
                News = news
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult GetNews(int newsId)
        {
            NewsModel news = this.newsService.NewsById(newsId);

            return View("_ShowNews", news);
        }

        [HttpGet]
        public IActionResult GetMoreNews(int skip)
        {
            IList<NewsModel> news = this.newsService.GetNewsWithTake(skip, take);
            long newsShown = this.newsService.GetNewsWithTake(0, skip + take).Count;
            long newsCount = this.newsService.CountAllNews();

            NewsPageModel model = new NewsPageModel
            {
                Skip = skip + take,
                HasMore = newsCount > newsShown,
                News = news
            };

            return PartialView("_NewsList", model);
        }

        [HttpGet]
        public IActionResult AddNews()
        {
            return PartialView("_CreateNews");
        }

        [HttpPost]
        public IActionResult AddNews(NewsFormModel model)
        {
            this.newsService.Create(model.Title, model.Text, model.ShortDescription, model.Photo, model.IsFavorite);

            return RedirectToAction("Index", "Admin", new { categoryId = 3 });
        }

        [HttpGet]
        public IActionResult EditNews(int newsId)
        {
            NewsModel news = this.newsService.NewsById(newsId);

            NewsFormModel model = new NewsFormModel
            {
                NewsId = news.Id,
                Title = news.Title,
                ShortDescription = news.ShortDescription,
                Text = news.Text,
                IsFavorite = news.IsFavorite,
            };

            return PartialView("_EditNews", model);
        }

        [HttpPost]
        public IActionResult EditNews(NewsFormModel model)
        {
            this.newsService.Edit(
                model.NewsId,
                model.Title,
                model.Text,
                model.ShortDescription,
                model.Photo,
                model.IsFavorite
                );

            return RedirectToAction("Index", "Admin", new { categoryId = 3 });
        }

        [HttpDelete]
        public IActionResult DeleteNews(int newsId)
        {
            this.newsService.Delete(newsId);

            return Json(new { message = "Успішно видалено" });
        }
    }
}

Musicorum/Musicorum/Controllers/SongsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Musicorum.Services;
using Musicorum.Services.Classes;
using Musicorum.Services.Models;
using Musicorum.Web.Extensions;
using Musicorum.Web.Models.Songs;

namespace Musicorum.Web.Controllers
{
    public class SongsController : Controller
    {
        private readonly ISongService songService;
        private readonly ICommentService commentService;
        private readonly IGenreService genreService;
        private readonly IUserService userService;

        public SongsController(ISongService songService, ICommentService commentService, IGenreService genreService, IUserService userService)
        {
            this.songService = songService;
            this.commentService = commentService;
            this.genreService = genreService;
            this.userService = userService;
        }

        [HttpPost]
        [Authorize]
        public IActionResult Like(int songId)
        {
            bool added = this.songService.Like(songId, User.GetUserId());

            return Json(added);
        }

        [HttpGet]
        public IActionResult GetSong(int songId)
        {
            SongModel song = this.songService.SongById(songId, User.GetUserId());
            IEnumerable<CommentModel> comments = this.commentService.CommentsBySongId(songId);

            song.Comments = comments;

            return View("_SongPage", song);
        }

        [HttpGet]
        public IActionResult Index()
        {
            IList<SongModel> songs = this.songService.GetSongs(User.GetUserId());
            IList<GenreModel> genres = this.genreService.AllGenres();

            SongsPageModel model = new SongsPageModel
            {
                Songs = songs,
                Genres = genres,
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult GenrePage(int genreId)
        {
            GenreModel genre = this.genreService.GenreById(genreId);

            IList<SongModel> songs = this.songService.GetSongsOfGenre(genreId, User.GetUserId());

            GenrePageModel model = new GenrePageModel
            {
                Genre = genre,
                SongsOfGenre = songs,
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Search(string query)
        {
            IList<SongModel> songs = this.songService.GetSongsByTitle(query, User.GetUserId());
            IList<GenreModel> genres = this.genreService.AllGenres();

            SearchResultModel model = new SearchResultModel
            {
                Songs = songs,
                Genres = genres,
                Query = query,
            };

            return View("SearchResult", model);
        }

        [HttpGet]
        public IActionResult AddSong(bool isAdminPage = false)
        {
            IList<GenreModel> genres = this.genreService.AllGenres();

            SongFormModel model = new SongFormModel
            {
                Genres = genres,
                IsAdminPage = isAdminPage,
            };

            return PartialView("Create", model);
        }

        [HttpPost]
        public IActionResult AddSong(SongFormModel model)
        {
            UserModel user = userService.GetById(User.GetUserId());

            this.songService.Create(
                model.Title,
                model.Description,
                model.Chorus,
                model.Song,
                model.Photo,
                User.GetUserId(),
                model.GenreId,
                string.IsNullOrEmpty(model.Author) ? $"{user.FirstName} {user.LastName}" : model.Author);

            if (model.IsAdminPage)
            {
                return RedirectToAction("Index", "Admin", new { categoryId = 1 });
            }


            return RedirectToAction("AccountDetails", "Users", User.GetUserId());
        }

        [HttpGet]
        public IActionResult EditSong(int songId, bool isAdminPage = false)
        {
            SongModel song = songService.SongById(songId, User.GetUserId());
            IList<GenreModel> genres = this.genreService.AllGenres();

            SongFormModel model = new SongFormModel {
                SongId = song.Id,
                Title = song.Title,
                Description = song.Description,
                Chorus = song.Chorus,
                GenreId = song.Genre.Id,
                Genres = genres,
                IsEditPage = true,
                IsAdminPage = isAdminPage,
                Author = song.AuthorName,
            };

            return PartialView("Edit", model);
        }

        [HttpPost]
        public IActionResult EditSong(SongFormModel model)
        {
            this.songService.Edit(
                model.SongId,
                model.Title,
                model.Description,
                model.Chorus,
                model.GenreId,
                model.Song,
                model.Photo,
                model.Author
                );

            if (model.IsAdminPage)
            {
                return RedirectToAction("Index", "Admin", new { categoryId = 1 });
            }

            return PartialView("Edit", model);
        }

        [HttpDelete]
        public IActionResult DeleteSong(int songId)
        {
            songService.Delete(songId);

            return Json( new { message = "Успішно видалено"});
        }

        [HttpGet]
        public IActionResult AddGenre()
        {
            return PartialView("_CreateGenre");
        }

        [HttpPost]
        public IActionResult AddGenre(GenreFormModel model)
        {
            this.genreService.Create(model.Title, model.Description, model.Photo);

            return RedirectToAction("Index", "Admin", new { categoryId = 2 });
        }

        [HttpGet]
        public IActionResult EditGenre(int genreId)
        {
            GenreModel genre = this.genreService.GenreById(genreId);

            GenreFormModel model = new GenreFormModel
            {
                GenreId = genre.Id,
                Title = genre.Title,
                Description = genre.Description,
            };

            return PartialView("_EditGenre", model);
        }

        [HttpPost]
        public IActionResult EditGenre(GenreFormModel model)
        {
            this.genreService.Edit(
                model.GenreId,
                model.Title,
                model.Description,
                model.Photo
                );

            return RedirectToAction("Index", "Admin", new { categoryId = 2 });
        }

        [HttpDelete]
        public IActionResult DeleteGenre(int genreId)
        {
            this.genreService.Delete(genreId);

            return Json(new { message = "Успішно видалено" });
        }
    }
}

Musicorum/Musicorum/Views/Admin/Index.cshtml
@model AdminModel

<div class="admin-container">
    <div class="admin-btns">
        <a href="@Url.Action("Index", "Admin", new { categoryId = 1})" class="@(Model.ChosenCategoryId == 1 ? "active" : string.Empty)">Пісні</a>
        <a href="@Url.Action("Index", "Admin", new { categoryId = 2})" class="@(Model.ChosenCategoryId == 2 ? "active" : string.Empty)">Жанри</a>
        <a href="@Url.Action("Index", "Admin", new { categoryId = 3})" class="@(Model.ChosenCategoryId == 3 ? "active" : string.Empty)">Новини</a>
        <a href="@Url.Action("Index", "Admin", new { categoryId = 4})" class="@(Model.ChosenCategoryId == 4 ? "active" : string.Empty)">Події</a>
    </div>
    <div class="admin-content">
        @switch (Model.ChosenCategoryId)
        {
            case 1:
            default:
                await Html.RenderPartialAsync("_SongsAdmin", Model.Songs);
                break;
            case 2:
                await Html.RenderPartialAsync("_GenresAdmin", Model.Genres);
                break;
            case 3:
                await Html.RenderPartialAsync("_NewsAdmin", Model.News);
                break;
            case 4:
                await Html.RenderPartialAsync("_EventsAdmin", Model.Events);
                break;
        }
    </div>
</div>

Musicorum/Musicorum/Views/Admin/_EventsAdmin.cshtml
@using Musicorum.Web.Models.Admin

@model AdminEventsModel

<div class="admin-songs-container">
    <div class="admin-add-btn add-event-btn" data-url="@Url.Action("AddEvent", "Events")">
        Додати подію
    </div>
    <div class="admin-songs">
        <div class="admin-songs-navs">
            <div class="admin-songs-sort">
                <div>Сортування:</div>
                <select class="admin-news-sort-select">
                    @if (Model.Sort == 1)
                    {
                        <option selected data-url="@Url.Action("GetEventsList", "Admin", new { sort = 1, query = Model.Query, page = Model.Page})">
                            Спочатку раніше додані
                        </option>
                    }
                    else
                    {
                        <option data-url="@Url.Action("GetEventsList", "Admin", new { sort = 1, query = Model.Query, page = Model.Page})">
                            Спочатку раніше додані
                        </option>
                    }

                    @if (Model.Sort == 2)
                    {
                        <option selected data-url="@Url.Action("GetEventsList", "Admin", new { sort = 2, query = Model.Query, page = Model.Page})">
                            Спочатку пізніше додані
                        </option>
                    }
                    else
                    {
                        <option data-url="@Url.Action("GetEventsList", "Admin", new { sort = 2, query = Model.Query, page = Model.Page})">
                            Спочатку пізніше додані
                        </option>
                    }
                </select>
            </div>
            <div class="admin-songs-search">
                <div class="input-group mb-3 search">
                    <input type="text" class="form-control admin-news-search-input" placeholder="Пошук" aria-label="Пошук" aria-describedby="button-addon2" value="@Model.Query">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary admin-news-search-btn" type="button" id="button-addon2" data-url="@Url.Action("GetEventsList", "Admin", new { sort = Model.Sort, page = Model.Page})">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="admin-songs-list">
            @if (Model.Events != null && Model.Events.Any())
            {
                <div class="admin-song">
                    <div class="admin-song-image tit tit-photo">Титульне фото</div>
                    <div class="admin-song-title tit">Назва</div>
                    <div class="admin-event-date tit">Місце проведення</div>
                    <div class="admin-event-date tit">Дата початку</div>
                    <div class="admin-event-date tit">Дата кінця</div>
                    <div class="tit tit-edit">Редагувати</div>
                    <div class="tit tit-del">Видалити</div>
                </div>

                @foreach (EventModel eventt in Model.Events)
                {
                    <div class="admin-song admin-event">
                        <div class="admin-song-image">
                            <img src="@eventt.ImageUrl" />
                        </div>
                        <div class="admin-song-title">@eventt.Title</div>
                        <div class="admin-event-date">@eventt.Location</div>
                        <div class="admin-event-date">@eventt.DateStarts</div>
                        <div class="admin-event-date">@eventt.DateEnds</div>
                        <div class="admin-event-edit" data-url="@Url.Action("EditEvent", "Events", new { eventId = eventt.Id})"><i class="fa fa-edit"></i></div>
                        <div class="admin-event-delete" data-id="@eventt.Id" data-url="@Url.Action("DeleteEvent", "Events")"><i class="fa fa-remove"></i></div>
                    </div>
                }
            }
            else
            {
                <div>
                    Нічого не знайдено
                </div>
            }
        </div>
        <div class="admin-songs-pages">
            @for (int i = 1; i <= Model.PageCount; i++)
            {
                <div class="admin-event-page @(i == Model.Page ? "active" : string.Empty)" data-url="@Url.Action("GetEventsList", "Admin", new { sort = Model.Sort, query = Model.Query, page = i})">@i</div>
            }
        </div>
    </div>
</div>

Musicorum/Musicorum/Views/Admin/_GenresAdmin.cshtml
@using Musicorum.Web.Models.Admin

@model AdminGenresModel

<div class="admin-songs-container">
    <div class="admin-add-btn add-genre-btn" data-url="@Url.Action("AddGenre", "Songs")">
        Додати жанр
    </div>
    <div class="admin-songs">
        <div class="admin-genres-navs">
            <div class="admin-songs-search">
                <div class="input-group mb-3 search">
                    <input type="text" class="form-control admin-genres-search-input" placeholder="Пошук" aria-label="Пошук" aria-describedby="button-addon2" value="@Model.Query">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary admin-genres-search-btn" type="button" id="button-addon2" data-url="@Url.Action("GetGenresList", "Admin", new { page = Model.Page})">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="admin-songs-list">
            @if (Model.Genres != null && Model.Genres.Any())
            {
                <div class="admin-song">
                    <div class="admin-song-image tit tit-photo">Титульне фото</div>
                    <div class="admin-song-title tit">Назва</div>
                    <div class="admin-genres-desc tit">Опис</div>
                    <div class="tit tit-edit">Редагувати</div>
                    <div class="tit tit-del">Видалити</div>
                </div>

                @foreach (GenreModel genre in Model.Genres)
                {
                    <div class="admin-song admin-genre">
                        <div class="admin-song-image">
                            <img src="@genre.TitlePhoto.ToRenderablePictureString()" />
                        </div>
                        <div class="admin-song-title">@genre.Title</div>
                        <div class="admin-genres-desc">@genre.Description</div>
                        <div class="admin-genre-edit" data-url="@Url.Action("EditGenre", "Songs", new { genreId = genre.Id})"><i class="fa fa-edit"></i></div>
                        <div class="admin-genre-delete" data-id="@genre.Id" data-url="@Url.Action("DeleteGenre", "Songs")"><i class="fa fa-remove"></i></div>
                    </div>
                }
            }
            else
            {
                <div>
                    Нічого не знайдено
                </div>
            }
        </div>
        <div class="admin-songs-pages">
            @for (int i = 1; i <= Model.PageCount; i++)
            {
                <div class="admin-genres-page @(i == Model.Page ? "active" : string.Empty)" data-url="@Url.Action("GetGenresList", "Admin", new { query = Model.Query, page = i})">@i</div>
            }
        </div>
    </div>
</div>

Musicorum/Musicorum/Views/Admin/_NewsAdmin.cshtml
@using Musicorum.Web.Models.Admin

@model AdminNewsModel

<div class="admin-songs-container">
    <div class="admin-add-btn add-news-btn" data-url="@Url.Action("AddNews", "News")">
        Додати новину
    </div>
    <div class="admin-songs">
        <div class="admin-songs-navs">
            <div class="admin-songs-sort">
                <div>Сортування:</div>
                <select class="admin-news-sort-select">
                    @if (Model.Sort == 1)
                    {
                        <option selected data-url="@Url.Action("GetNewsList", "Admin", new { sort = 1, query = Model.Query, page = Model.Page})">
                            Спочатку раніше додані
                        </option>
                    }
                    else
                    {
                        <option data-url="@Url.Action("GetNewsList", "Admin", new { sort = 1, query = Model.Query, page = Model.Page})">
                            Спочатку раніше додані
                        </option>
                    }

                    @if (Model.Sort == 2)
                    {
                        <option selected data-url="@Url.Action("GetNewsList", "Admin", new { sort = 2, query = Model.Query, page = Model.Page})">
                            Спочатку пізніше додані
                        </option>
                    }
                    else
                    {
                        <option data-url="@Url.Action("GetNewsList", "Admin", new { sort = 2, query = Model.Query, page = Model.Page})">
                            Спочатку пізніше додані
                        </option>
                    }
                </select>
            </div>
            <div class="admin-songs-search">
                <div class="input-group mb-3 search">
                    <input type="text" class="form-control admin-news-search-input" placeholder="Пошук" aria-label="Пошук" aria-describedby="button-addon2" value="@Model.Query">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary admin-news-search-btn" type="button" id="button-addon2" data-url="@Url.Action("GetNewsList", "Admin", new { sort = Model.Sort, page = Model.Page})">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="admin-songs-list">
            @if (Model.News != null && Model.News.Any())
            {
            <div class="admin-song">
                <div class="admin-song-image tit tit-photo">Титульне фото</div>
                <div class="admin-song-title tit">Назва</div>
                <div class="admin-genres-desc tit">Короткий опис</div>
                <div class="tit tit-edit">Редагувати</div>
                <div class="tit tit-del">Видалити</div>
            </div>

                @foreach (NewsModel news in Model.News)
                {
                    <div class="admin-song admin-news">
                        <div class="admin-song-image">
                            <img src="@news.Photo.ToRenderablePictureString()" />
                        </div>
                        <div class="admin-song-title">@news.Title</div>
                        <div class="admin-genres-desc">@news.ShortDescription</div>
                        <div class="admin-news-edit" data-url="@Url.Action("EditNews", "News", new { newsId = news.Id})"><i class="fa fa-edit"></i></div>
                        <div class="admin-news-delete" data-id="@news.Id" data-url="@Url.Action("DeleteNews", "News")"><i class="fa fa-remove"></i></div>
                    </div>
                }
            }
            else
            {
                <div>
                    Нічого не знайдено
                </div>
            }
        </div>
        <div class="admin-songs-pages">
            @for (int i = 1; i <= Model.PageCount; i++)
            {
                <div class="admin-news-page @(i == Model.Page ? "active" : string.Empty)" data-url="@Url.Action("GetNewsList", "Admin", new { sort = Model.Sort, query = Model.Query, page = i})">@i</div>
            }
        </div>
    </div>
</div>